ServerName ${APACHE_SERVER_NAME}

<VirtualHost *:80>
    ServerName ${APACHE_SERVER_NAME}
    Redirect permanent / ${NEXTCLOUD_URL}/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName ${APACHE_SERVER_NAME}
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile /etc/apache2/tls/tls.crt
    SSLCertificateKeyFile /etc/apache2/tls/tls.key

    <Directory /var/www/html>
        Require all granted
        AllowOverride All
        Options FollowSymLinks MultiViews
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
